//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JASDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.Journals = new HashSet<Journal>();
            this.Journals1 = new HashSet<Journal>();
        }
    
        public string AccountName { get; set; }
        public string AccountType { get; set; }
        public double DebitBalance { get; set; }
    
        public virtual ICollection<Journal> Journals { get; set; }
        public virtual ICollection<Journal> Journals1 { get; set; }
    }
}
