//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JASDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Receipt_Sale = new HashSet<Receipt_Sale>();
        }
    
        public int Customer_Id { get; set; }
        public string CustomerName { get; set; }
        public string CustomerAddress { get; set; }
        public Nullable<int> CustomerPhone { get; set; }
    
        public virtual ICollection<Receipt_Sale> Receipt_Sale { get; set; }
    }
}
