//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JASDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpPay
    {
        public int EmpId { get; set; }
        public double Salary { get; set; }
        public double Commission { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
