//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JASDataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JASDataSource : DbContext
    {
        public JASDataSource()
            : base("name=JASDataSource")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmpPay> EmpPays { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Journal> Journals { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Receipt_Purchase> Receipt_Purchase { get; set; }
        public virtual DbSet<Receipt_Sale> Receipt_Sale { get; set; }
        public virtual DbSet<Seller> Sellers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tile> Tiles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<TileStock> TileStocks { get; set; }
    }
}
