//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JASDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal
    {
        public int EntryNo { get; set; }
        public string DebitAc { get; set; }
        public string CreditAc { get; set; }
        public double DebitAmount { get; set; }
        public double CreditAmount { get; set; }
        public string Description { get; set; }
        public System.DateTime TransDate { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
    }
}
