//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JASDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt_Sale
    {
        public int ReceiptNo { get; set; }
        public System.DateTime SaleDate { get; set; }
        public int CustomerId { get; set; }
        public string TileId { get; set; }
        public int Count { get; set; }
        public Nullable<double> DeliveryCost { get; set; }
        public string Description { get; set; }
        public double Price { get; set; }
        public double Total { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual Tile Tile { get; set; }
    }
}
