//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JASDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt_Purchase
    {
        public int ReceiptNo { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public int Qty { get; set; }
        public int SellerId { get; set; }
        public double DeliveryCost { get; set; }
        public double Price { get; set; }
        public double Total { get; set; }
        public string Description { get; set; }
        public byte[] ItemId { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual Seller Seller { get; set; }
    }
}
