//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JASDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seller
    {
        public Seller()
        {
            this.Receipt_Purchase = new HashSet<Receipt_Purchase>();
        }
    
        public int SellerId { get; set; }
        public string SellerName { get; set; }
        public Nullable<int> SellerPhone { get; set; }
        public string SellerAddress { get; set; }
    
        public virtual ICollection<Receipt_Purchase> Receipt_Purchase { get; set; }
    }
}
