//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JASDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TileStock
    {
        public string TileId { get; set; }
        public int Qty { get; set; }
        public System.DateTime DateQtyUpdate { get; set; }
        public int QtySold { get; set; }
    
        public virtual Tile Tile { get; set; }
    }
}
