//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JASDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tile
    {
        public Tile()
        {
            this.Receipt_Sale = new HashSet<Receipt_Sale>();
            this.TileStocks = new HashSet<TileStock>();
        }
    
        public string TileID { get; set; }
        public string TileName { get; set; }
        public string TileSize { get; set; }
        public string TileColor { get; set; }
        public double TilePrice { get; set; }
    
        public virtual ICollection<Receipt_Sale> Receipt_Sale { get; set; }
        public virtual ICollection<TileStock> TileStocks { get; set; }
    }
}
